name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint
        env:
          HA_BASE_URL: ${{ secrets.HA_BASE_URL }}
          HA_TOKEN: ${{ secrets.HA_TOKEN }}

      - name: Test
        run: bun test
        env:
          HA_BASE_URL: ${{ secrets.HA_BASE_URL }}
          HA_TOKEN: ${{ secrets.HA_TOKEN }}
