name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint
        env:
          HA_BASE_URL: ${{ secrets.HA_BASE_URL }}
          HA_TOKEN: ${{ secrets.HA_TOKEN }}

      - name: Test
        run: bun test
        env:
          HA_BASE_URL: ${{ secrets.HA_BASE_URL }}
          HA_TOKEN: ${{ secrets.HA_TOKEN }}

      - name: Build
        run: bun run build:all

      - name: Upload dist folder as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/
          retention-days: ${{ startsWith(github.ref, 'refs/tags/') && 0 || 7 }}

  docker:
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=short

      # Build and push AMD64 image
      - name: Build and push AMD64
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}:amd64-${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      # Create a multi-arch manifest
      - name: Create and push multi-arch manifest
        run: |
          # Install Docker Manifest tool
          DOCKER_CLI_EXPERIMENTAL=enabled

          # For each tag from metadata
          for tag in $(echo '${{ steps.meta.outputs.tags }}' | tr '\n' ' '); do
            # Create manifest with only the AMD64 image
            docker manifest create $tag ghcr.io/${{ github.repository }}:amd64-${{ github.sha }}
            
            # Add ARM64 platform support (points to same image)
            docker manifest annotate $tag ghcr.io/${{ github.repository }}:amd64-${{ github.sha }} --arch arm64 --os linux
            
            # Push the manifest
            docker manifest push $tag
          done

      - name: Create GitHub Release for tags
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: false
