name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint
        env:
          HA_BASE_URL: ${{ secrets.HA_BASE_URL }}
          HA_TOKEN: ${{ secrets.HA_TOKEN }}

      - name: Test
        run: bun test
        env:
          HA_BASE_URL: ${{ secrets.HA_BASE_URL }}
          HA_TOKEN: ${{ secrets.HA_TOKEN }}

      - name: Build
        run: bun run build:all

      - name: Upload dist folder as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/
          retention-days: ${{ startsWith(github.ref, 'refs/tags/') && 0 || 7 }}

  docker:
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.arch }}
            type=ref,event=tag,suffix=-${{ matrix.arch }}
            type=sha,format=short,suffix=-${{ matrix.arch }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            ARCH=${{ matrix.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create GitHub Release for tags
        if: startsWith(github.ref, 'refs/tags/') && matrix.arch == 'x64'
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: false

  manifest:
    needs: docker
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        uses: Noelware/docker-manifest-action@0.4.0
        with:
          inputs: ghcr.io/${{ github.repository }}:${{ github.ref_name == 'main' && 'main' || github.ref_name }},ghcr.io/${{ github.repository }}:${{ github.ref_name == 'main' && 'main' || github.ref_name }}-x64,ghcr.io/${{ github.repository }}:${{ github.ref_name == 'main' && 'main' || github.ref_name }}-arm64
          push: true

      - name: Create and push sha manifest
        if: github.ref == 'refs/heads/main'
        uses: Noelware/docker-manifest-action@0.4.0
        with:
          inputs: ghcr.io/${{ github.repository }}:sha-${{ github.sha }},ghcr.io/${{ github.repository }}:sha-${{ github.sha }}-x64,ghcr.io/${{ github.repository }}:sha-${{ github.sha }}-arm64
          push: true
